# Generated by Django 3.0.7 on 2020-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='Major',
            field=models.CharField(max_length=10),
        ),
    ]
