# Generated by Django 3.0.7 on 2020-06-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectmember',
            name='preferential',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collectteam',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
