# Generated by Django 3.0.7 on 2020-07-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200701_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='Major',
            new_name='major',
        ),
    ]
