# Generated by Django 3.0.7 on 2020-07-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200714_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collect_team', to='teams.Team'),
        ),
    ]
