# Generated by Django 3.0.7 on 2020-07-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200701_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='finalMembers',
        ),
    ]
