# Generated by Django 2.1.15 on 2020-07-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_finalmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='currentMembers',
            new_name='current_members',
        ),
    ]
