# Generated by Django 2.1.15 on 2020-07-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200704_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectteam',
            name='oneline_description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
