# Generated by Django 2.1.15 on 2020-07-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_collectteam_oneline_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectteam',
            old_name='collectCount',
            new_name='collect_count',
        ),
    ]
