# Generated by Django 2.1.15 on 2020-07-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20200704_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectmembermajor',
            name='collect_member',
        ),
        migrations.RemoveField(
            model_name='collectmembermajor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='collectmember',
            name='major',
        ),
        migrations.AddField(
            model_name='collectmember',
            name='major',
            field=models.CharField(default='무관', max_length=10),
        ),
        migrations.DeleteModel(
            name='CollectMemberMajor',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
