# Generated by Django 2.1.15 on 2020-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200705_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectmemberrole',
            name='collect_member',
        ),
        migrations.RemoveField(
            model_name='collectmemberrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='collectmember',
            name='role',
        ),
        migrations.AddField(
            model_name='collectmember',
            name='role',
            field=models.CharField(default='무관', max_length=10),
        ),
        migrations.DeleteModel(
            name='CollectMemberRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
