# Generated by Django 2.1.15 on 2020-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20200705_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectmember',
            name='role',
            field=models.CharField(default='무관', max_length=30),
        ),
    ]
