# Generated by Django 3.0.7 on 2020-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200706_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelanguage',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
