# Generated by Django 2.1.15 on 2020-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200705_0013'),
        ('boards', '0003_auto_20200704_1733'),
    ]

    operations = [
    ]
